In [6]:
import pandas as pd
import numpy as np

In [7]:
file_path = 'Historical Returns.xlsx'
df = pd.read_excel(file_path, skiprows=1)
df.columns = ["Scheme_Name", "Plan", "Category", "Crisil_Rating", "AuM", "1W", "1M", "3M", "6M", "YTD", "1Y", "2Y", "3Y", "5Y", "10Y"]

In [8]:
df

,Scheme_Name,Plan,Category,Crisil_Rating,AuM,1W,1M,3M,6M,YTD,1Y,2Y,3Y,5Y,10Y
0,Invesco India Contra Fund - Direct Plan - Growth,Direct Plan,Contra Fund,3,18469.89,0.0090,-0.0350,0.0262,0.1970,0.3133,0.4733,0.3018,0.2015,0.2411,0.1824
1,SBI Contra Fund - Direct Plan - Growth,Direct Plan,Contra Fund,4,41326.63,0.0070,-0.0321,-0.0130,0.1111,0.2139,0.3693,0.3037,0.2378,0.31,0.1739
2,SBI Contra Fund - Regular Plan - Growth,Regular,Contra Fund,4,41326.63,0.0068,-0.0328,-0.0154,0.1057,0.2039,0.3564,0.2915,0.2269,0.2998,0.1655
3,Franklin India ELSS Tax Saver Fund - Direct Pl...,Direct Plan,ELSS,4,6832.69,0.0112,-0.0282,0.0089,0.1349,0.2255,0.3709,0.2700,0.1835,0.2168,0.1517
4,Franklin India ELSS Tax Saver Fund - Growth,Regular,ELSS,4,6832.69,0.0110,-0.0288,0.0068,0.1303,0.2172,0.3603,0.2595,0.1738,0.2064,0.1413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Axis Value Fund - Regular Plan - Growth,Regular,Value Fund,4,749.48,0.0039,-0.0318,0.0133,0.1789,0.2691,0.4297,0.3198,0.1995,-,-
162,ICICI Prudential Value Discovery Fund - Direct...,Direct Plan,Value Fund,4,49104.38,0.0036,-0.0270,-0.0022,0.1336,0.2341,0.3714,0.2832,0.2208,0.2661,0.1656
163,ICICI Prudential Value Discovery Fund - Growth,Regular,Value Fund,4,49104.38,0.0035,-0.0275,-0.0036,0.1305,0.2282,0.3638,0.2764,0.2142,0.2593,0.1566
164,JM Value Fund - (Direct) - Growth,Direct Plan,Value Fund,5,1066.84,-0.0031,-0.0349,-0.0272,0.1382,0.2867,0.4438,0.3960,0.2512,0.2602,0.1876
165,JM Value Fund - Growth,Regular,Value Fund,5,1066.84,-0.0034,-0.0359,-0.0305,0.1306,0.2719,0.4259,0.3826,0.2404,0.2504,0.1762

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Scheme_Name    166 non-null    object
 1   Plan           166 non-null    object
 2   Category       166 non-null    object
 3   Crisil_Rating  166 non-null    object
 4   AuM            166 non-null    float64
 5   1W             166 non-null    float64
 6   1M             166 non-null    float64
 7   3M             166 non-null    float64
 8   6M             166 non-null    float64
 9   YTD            166 non-null    float64
 10  1Y             166 non-null    float64
 11  2Y             166 non-null    float64
 12  3Y             166 non-null    object
 13  5Y             166 non-null    object
 14  10Y            166 non-null    object
dtypes: float64(8), object(7)
memory usage: 19.6+ KB

In [14]:
df[['3Y', '5Y', '10Y']] = df[['3Y', '5Y', '10Y']].replace("-", np.nan)
df[['3Y', '5Y', '10Y']] = df[['3Y', '5Y', '10Y']].infer_objects(copy=False).astype(float)

In [15]:
df['3Y'] = df['3Y'].fillna(df['3Y'].median())
df['5Y'] = df['5Y'].fillna(df['5Y'].median())
df['10Y'] = df['10Y'].fillna(df['10Y'].median())

In [16]:
print(df[['3Y', '5Y', '10Y']].tail())

         3Y      5Y     10Y
161  0.1995  0.2367  0.1584
162  0.2208  0.2661  0.1656
163  0.2142  0.2593  0.1566
164  0.2512  0.2602  0.1876
165  0.2404  0.2504  0.1762

In [ ]:
# Function to get top performers for each category
def get_top_performers(df, category, top_n=5):
    # Filter the data for the selected category
    category_df = df[df['Category'] == category]
    
    # Sorting by 3Y returns (you can also sort by 1Y, 5Y, etc., based on user preference)
    top_performers = category_df.sort_values(by='3Y', ascending=False).head(top_n)
    
    return top_performers[['Scheme_Name', 'Category', 'Crisil_Rating', 'AuM', '1Y', '3Y', '5Y']]